from pptx import Presentation
from pptx.util import Pt
import os

# Absolute path anchored to this file's location, same reasoning as
# pdfmaker.py: don't depend on the process's current working directory.
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_FOLDER = os.path.join(BASE_DIR, "generated_presentations")


def create_presentation(
    title: str,
    slides: list,
    filename: str = "presentation.pptx"
):

    os.makedirs(OUTPUT_FOLDER, exist_ok=True)

    filepath = os.path.join(OUTPUT_FOLDER, filename)

    prs = Presentation()

    # -----------------------------
    # Title Slide
    # -----------------------------
    layout = prs.slide_layouts[0]

    slide = prs.slides.add_slide(layout)

    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by AI Agent"

    # -----------------------------
    # Content Slides
    # -----------------------------
    for item in slides:

        layout = prs.slide_layouts[1]

        slide = prs.slides.add_slide(layout)

        slide.shapes.title.text = item.get("title", "Untitled")

        body = slide.placeholders[1].text_frame
        body.clear()

        for line in item.get("content", "").split("\n"):
            p = body.add_paragraph()
            p.text = line
            p.level = 0
            p.font.size = Pt(22)

    prs.save(filepath)

    return filepath


# -------------------------------------------------
# Tool entry point
# -------------------------------------------------

def execute(arguments: dict):

    title = arguments.get("title", "Presentation")
    slides = arguments.get("slides", [])
    filename = arguments.get("filename", "presentation.pptx")

    try:
        filepath = create_presentation(
            title=title,
            slides=slides,
            filename=filename
        )

    except Exception as e:
        return {
            "type": "ppt",
            "file": None,
            "message": f"Failed to create presentation: {e}"
        }

    return {
        "type": "ppt",
        "file": filepath,
        "message": f"Presentation '{filename}' created successfully."
    }


if __name__ == "__main__":

    print(
        execute(
            {
                "title": "AI Presentation",
                "filename": "AI_Presentation.pptx",
                "slides": [
                    {
                        "title": "Introduction",
                        "content": "Artificial Intelligence\nMachine Learning"
                    },
                    {
                        "title": "Applications",
                        "content": "Healthcare\nFinance\nEducation"
                    }
                ]
            }
        )
    )