from pptx import Presentation
from pptx.util import Inches, Pt
import os

OUTPUT_FOLDER = "generated_presentations"


def create_presentation(
    title: str,
    slides: list,
    filename: str = "presentation.pptx"
) -> str:
    """
    Creates a PowerPoint presentation.

    Parameters
    ----------
    title : str
        Presentation title

    slides : list
        Example:
        [
            {
                "title": "Introduction",
                "content": "This is the introduction."
            },
            {
                "title": "Applications",
                "content": "Machine Learning\nData Science\nAI"
            }
        ]

    filename : str

    Returns
    -------
    str
        Path of generated presentation.
    """

    os.makedirs(OUTPUT_FOLDER, exist_ok=True)

    filepath = os.path.join(OUTPUT_FOLDER, filename)

    prs = Presentation()

    # -----------------------------
    # Title Slide
    # -----------------------------
    layout = prs.slide_layouts[0]

    slide = prs.slides.add_slide(layout)

    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by AI Agent"

    # -----------------------------
    # Content Slides
    # -----------------------------
    for item in slides:

        layout = prs.slide_layouts[1]

        slide = prs.slides.add_slide(layout)

        slide.shapes.title.text = item.get("title", "Untitled")

        body = slide.placeholders[1].text_frame

        body.clear()

        for line in item.get("content", "").split("\n"):

            p = body.add_paragraph()
            p.text = line
            p.level = 0
            p.font.size = Pt(22)

    prs.save(filepath)

    return filepath


if __name__ == "__main__":

    slides = [

        {
            "title": "Introduction",
            "content": "Artificial Intelligence\nMachine Learning\nDeep Learning"
        },

        {
            "title": "Applications",
            "content": "Healthcare\nFinance\nEducation\nRobotics"
        },

        {
            "title": "Conclusion",
            "content": "AI is transforming every industry."
        }

    ]

    path = create_presentation(
        title="Introduction to AI",
        slides=slides,
        filename="AI_Presentation.pptx"
    )

    print(path)